### ISSUE TITLE
multiple instances on ui 

### ISSUE THREAD

**Issue by vikingsraven** [Christian-Me/node-red-contrib-ui-uplot-charts#1]
HI, as per forum post,  thanks for creating this 

Win10
node-red 2.1.0
npm version  6.14.15
node version 14.17.6

each time flow is deployed a new instance appears on the ui page, doesn't contain anything  but the instance is put into the first one underneath it, But doesn't show chart info.
Also occasionally the left hand values don't appear, neither does the chart plot , but on refresh of page it shows chart in first instance.
used Brave and chrome to have a check and its the same in both

**Comment by vikingsraven** [comment]
hi sorry been , working away from home, back now so can have a look and follow up

**Comment by vikingsraven** [comment]
hi , just uploaded 0.0.6, ran the speed test script, deployed came up fine, redeployed another widget opened as before.
Sorry

**Comment by vikingsraven** [comment]
HI, ok back onto this. 
When i have deleted the Tabs and the groups that had the uplots chart in it , i refreshed the web browser after deploying and none of the ui pages for the uplot graphs go. so i have 3 tabs that are no existent.
![image](https://user-images.githubusercontent.com/11271233/153900398-82d5c9ed-f2d1-4125-9646-d2c91c25b2e7.png)
and the Dashboard UI tabs shows 
![image](https://user-images.githubusercontent.com/11271233/153900629-d02177fd-3342-4a0e-8aca-0c3ec52dcff5.png)

**Comment by vikingsraven** [comment]
interestingly , when i went to assign a new UI Group to the Uplot unit after removing the old Tabs i got this.
 
![image](https://user-images.githubusercontent.com/11271233/153902614-9efc40ea-05da-4a82-9249-ecb4b74348f0.png)
```

TypeError: Cannot read property 'id' of null
    at new uPlotUINode (C:\Users\MarkStillman\.node-red\node_modules\node-red-contrib-ui-uplot-charts\ui-uplot-charts.js:351:40)
    at Object.createNode (C:\Users\MarkStillman\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\flows\util.js:89:27)
    at Flow.start (C:\Users\MarkStillman\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\flows\Flow.js:206:48)
    at start (C:\Users\MarkStillman\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\flows\index.js:371:33)```

**Comment by Christian-Me** [comment]
Thank you for your feedback.
Just wonder if you tried to setup a chart from scratch without using the examples.
What happens after full deploy or even restart?

Think I have to setup a unmodified node red instance to check the demos before deployment. It is much easier to fix a bug if I can reproduce it.
But beside this going through your posts again I came up with new ideas to look into.
Thanx! Sorry for the delays.

**Comment by vikingsraven** [comment]
hi no probs.
ive just pulled the staright node in this time into a project im working on. i set the size to 12 x 4 , but its appearing in screen as a full width widget.
Also i have added 2 sources Solar_in and Batt_Out , when i deploy it has 4 series appear  series 3 is s duplicate of series 1 and series 4 has no name, if i delete them and then deploy they come back.
![image](https://user-images.githubusercontent.com/11271233/154977816-0ab43fa8-e24f-4f5e-8006-a0ad3aaa8944.png)

see below code, the graph should appear between the 2 gauges!
[gaugetes.txt](https://github.com/Christian-Me/node-red-contrib-ui-uplot-charts/files/8110144/gaugetes.txt)

**Comment by vikingsraven** [comment]
couldnt work out how to download the inspection file on brave so cut and paste it here, so nothing in noe red- before restart but showing the 6 graph ui instances on the main ui page 
![image](https://user-images.githubusercontent.com/11271233/154982144-546856f1-d7ce-4cb0-9189-31e5a9a8a864.png)

it apperas they all have same node id , i have copied contents of the ui panel section
![image](https://user-images.githubusercontent.com/11271233/154982653-f562ac6c-6a2d-4ad9-b5fa-4d13e04dcc1a.png)

on restart of node red all clear! i hope info is helpful, dont want to put too much onto you!

**Comment by vikingsraven** [comment]
reloaded  added graphui , then on deploy got this 
```
21 Feb 15:33:08 - [info] Stopping flows
21 Feb 15:33:08 - [info] Stopped flows
21 Feb 15:33:08 - [info] Starting flows
undefined undefined
ReferenceError: _node is not defined
    at checkConfig (C:\Users\MarkStillman\.node-red\node_modules\node-red-contrib-ui-uplot-charts\ui-uplot-charts.js:45:13)
    at new uPlotUINode (C:\Users\MarkStillman\.node-red\node_modules\node-red-contrib-ui-uplot-charts\ui-uplot-charts.js:344:17)
    at Object.createNode (C:\Users\MarkStillman\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\flows\util.js:89:27)
    at Flow.start (C:\Users\MarkStillman\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\flows\Flow.js:206:48)
    at start (C:\Users\MarkStillman\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\flows\index.js:371:33)
21 Feb 15:33:08 - [info] Started flows
```
looking at the commandline i got this earlier but missed it
```
21 Feb 14:48:05 - [info] [worldmap:cce85a8be52ce929] started at /worldmap
undefined memory
TypeError: Cannot read property 'id' of null
    at new uPlotUINode (C:\Users\MarkStillman\.node-red\node_modules\node-red-contrib-ui-uplot-charts\ui-uplot-charts.js:351:40)
    at Object.createNode (C:\Users\MarkStillman\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\flows\util.js:89:27)
    at Flow.start (C:\Users\MarkStillman\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\flows\Flow.js:206:48)
    at start (C:\Users\MarkStillman\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\flows\index.js:371:33)
undefined memory
21 Feb 14:48:05 - [info] Started flows
```

**Comment by vikingsraven** [comment]
bit more , i just started looking at the ui-plot-charts.js. Im no coder in JavaScript but do some python.
i went n and put a console.log("killingplot") in line 686  to see if it was calling the $scope.uPlot.destroy(). well its getting into that part of the code fine on a redeploy, but it looks like uPlot.destroy() isn't doing anything!
from the uPlot.js 
```
	function destroy() {
		FEAT_CURSOR && sync.unsub(self);
		FEAT_CURSOR && cursorPlots.delete(self);
		mouseListeners.clear();
		off(dppxchange, win, syncPxRatio);
		root.remove();
		fire("destroy");
	}

	self.destroy = destroy;
```
cant see any bugs on the github pages  for it an no documentation either.

**Comment by Christian-Me** [comment]
> undefined memory
TypeError: Cannot read property 'id' of null
    at new uPlotUINode (C:\Users\MarkStillman\.node-red\node_modules\node-red-contrib-ui-uplot-charts\ui-uplot-charts.js:351:40)
    at Object.createNode (C:\Users\MarkStillman\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\flows\util.js:89:27)
    at Flow.start (C:\Users\MarkStillman\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\flows\Flow.js:206:48)
    at start (C:\Users\MarkStillman\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\flows\index.js:371:33)
undefined memory

This tells me that the the storage / context store is not configured correctly (and the error is not catched) I thought I solved the issue in the last update (on github)... Have to look into it - when I find some time.
